version: '3.7'

services:
    db:
        image: mysql:8.0
        volumes:
            - data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT_EXTERNAL}:3306

    php:
        build:
            context: ./
            dockerfile: ./docker/development/php-fpm/Dockerfile
        restart: always
        volumes:
            - ./:/app
        environment:
            DOMAIN_NAME: localhost
            APP_ENV: dev
            APP_SECRET: ${APP_SECRET}
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}
            TEST_DATABASE_URL: mysql://${MYSQL_ROOT_PASSWORD}:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_TEST_DATABASE}
        depends_on:
            - db

    nginx:
        build: docker/development/nginx
        restart: always
        ports:
            - ${NGINX_EXTERNAL_PORT}:80
        volumes:
            - ./:/app
            - ./docker/development/nginx/logs:/var/log/nginx

volumes:
    data:
